[project]
name = "langchain-tutorials"
version = "0.1.0"
description = "Langchain Tutorials"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "environs>=14.3.0",
    "langchain>=0.3.27",
    "langchain-openai>=0.3.33",
]
